# Generated by Django 2.1.7 on 2019-02-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_foodtype_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='marketprice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='productnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='storenums',
            field=models.IntegerField(default=0),
        ),
    ]
